name: rental_mobil
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-262.2.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.0
  go_router: ^13.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: 2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/family/
    - assets/commercial/
    - assets/luxury/
    - assets/icons/
